
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 22;
  public static final int especial = 19;
  public static final int coma = 13;
  public static final int numero = 17;
  public static final int flecha = 21;
  public static final int conj = 20;
  public static final int guion = 15;
  public static final int punto = 8;
  public static final int disyuncion = 12;
  public static final int llaveC = 3;
  public static final int EOF = 0;
  public static final int llaveA = 2;
  public static final int id = 16;
  public static final int puntocoma = 7;
  public static final int signo = 18;
  public static final int virgulilla = 14;
  public static final int error = 1;
  public static final int parentesisC = 5;
  public static final int asterisco = 9;
  public static final int mas = 10;
  public static final int interrogacion = 11;
  public static final int parentesisA = 4;
  public static final int dospuntos = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llaveA",
  "llaveC",
  "parentesisA",
  "parentesisC",
  "dospuntos",
  "puntocoma",
  "punto",
  "asterisco",
  "mas",
  "interrogacion",
  "disyuncion",
  "coma",
  "virgulilla",
  "guion",
  "id",
  "numero",
  "signo",
  "especial",
  "conj",
  "flecha",
  "cadena"
  };
}

